### ISSUE TITLE
Parsing with a custom formatting gives the wrong month

### ISSUE THREAD

**Issue by jamesnvc** [clj-time/clj-time#174]
I am very confused
```
user=> (clj-time.format/parse (clj-time.format/formatter "YYYY-MM-DD HH:mm:ss.SSSSSSZ") "2015-04-28 15:57:18.557348+00")
#<DateTime 2015-01-28T15:57:18.557Z>
```
Instead of the parsed date being in April, it's in January.  Using clj-time 0.9.0, Clojure 1.6.0, JVM 1.8.0_05-b13

**Comment by seancorfield** [comment]
I've reproduced this locally. Every month just maps to January. Odd.

**Comment by jamesnvc** [comment]
Very glad to hear I haven't just lost my mind, at least!

**Comment by seancorfield** [comment]
I repro'd with clj-time 0.10.0-SNAPSHOT built locally which uses Joda Time 2.7 -- since clj-time is such a thin wrapper around that library -- and got the same result. So I went to the Joda Time documentation... `DD` is "day of year", `dd` is "day of month". I'm afraid this is user error, you want:

    (clj-time.format/parse (clj-time.format/formatter "YYYY-MM-dd HH:mm:ss.SSSSSSZ") "2015-04-28 15:57:18.557348+00")

(and it should probably be `yyyy` not `YYYY`).

**Comment by jamesnvc** [comment]
Oh, oops. Sorry about that!
