### ISSUE TITLE
Add Instant to jdbc

### ISSUE THREAD

**Issue by arichiardi** [clj-time/clj-time#213]
Feature proposal: it would be great to add [Instant](http://www.joda.org/joda-time/apidocs/org/joda/time/Instant.html) to `clj-time.jdbc` with auto conversion.

It looks like it is the best candidate for Postgres' `TIMESTAMP WITHOUT TIME ZONE` fields.

**Comment by seancorfield** [comment]
I'm sure we'd consider a Pull Request that added this -- in a way that still allowed the rest of the library to continue to run on Java 7.

**Comment by arichiardi** [comment]
I was not talking about the new Java object, but about `org.joda.time/Instant`, was it introduced recently? Anyways I will try to come up with a PR :smile:

**Comment by michaelklishin** [comment]
@arichiardi if we're talking about Joda Time's types introduced recently, that's fine. We can bump the dependency. Depending on Clojure instants and thus bumping minimum required Clojure version is a different thing.

**Comment by seancorfield** [comment]
Ah, I didn't click on your link and after the addition of Java Time's Instant to Clojure itself, I just assumed that's what you were referring to, sorry, esp. since clj-time already has clj-time.instant (providing serialization of Joda Time's AbstractInstant) and many functions already support ReadableInstant.

Could you be a bit more specific about what additional Instant support you feel is needed?

**Comment by arichiardi** [comment]
I went to check the code, and probably only an addition to [this extend](https://github.com/clj-time/clj-time/blob/master/src/clj_time/jdbc.clj#L29) is needed in order to support either ` org.joda.time.Instant` or `ReadableInstant`

**Comment by seancorfield** [comment]
Hmm, I think you'd want to update `ICoerce` here https://github.com/clj-time/clj-time/blob/master/src/clj_time/coerce.clj#L119-L142 to support `Instant` with `to-date-time` (there's a `.toDateTime` method on `AbstractInstant`), and then change the `jdbc.clj` extension point to use `AbstractInstant`. Since all the `DateTime` types implement `AbstractInstant`, that might cause some ripple effects on `to-date-time` for other Joda types...?

**Comment by seancorfield** [comment]
@arichiardi Any forward movement on this or shall we close it?

**Comment by arichiardi** [comment]
On October 11, 2016 2:51:30 PM PDT, Sean Corfield <notifications@github.com> wrote:
>@arichiardi Any forward movement on this or shall we close it?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/clj-time/clj-time/issues/213#issuecomment-253057633

At the moment I have too many things queued up, but I suggest we keep it open as a reminder...if you want, in any case sooner or later it is a good thing to add I guess. Thank you Sean!
-ar

**Comment by arichiardi** [comment]
On October 11, 2016 2:51:30 PM PDT, Sean Corfield <notifications@github.com> wrote:
>@arichiardi Any forward movement on this or shall we close it?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/clj-time/clj-time/issues/213#issuecomment-253057633

At the moment I have too many things queued up, but I suggest we keep it open as a reminder...if you want, in any case sooner or later it is a good thing to add I guess. Thank you Sean!
-ar
-ar

**Comment by arichiardi** [comment]
On October 11, 2016 2:51:30 PM PDT, Sean Corfield <notifications@github.com> wrote:
>@arichiardi Any forward movement on this or shall we close it?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/clj-time/clj-time/issues/213#issuecomment-253057633

It is queued but the queue is at the moment full and no back pressure has been implemented yet :)

-ar

**Comment by seancorfield** [comment]
Since this has been open so long without a PR, I'm closing it now. Feel free to set yourself a reminder to send a PR if you still need this :) @arichiardi
