### ISSUE TITLE
Latest Cut of Master is stale?

### ISSUE THREAD

**Issue by AlexanderMann** [clj-time/clj-time#234]
# Motivation
`clj-time 0.13.0` is from November, and the latest changes to `master` are from March. I was hoping to start using the `spec` in production but found myself getting tripped up with:

```
 :cause "Unable to resolve spec: :clj-time.spec/date-time"
 :via
 [{:type java.lang.Exception
   :message "Unable to resolve spec: :clj-time.spec/date-time"
   :at [clojure.spec$reg_resolve_BANG_ invokeStatic "spec.clj" 70]}]

```

Curious as to what at this point is holding up a latest cut and if there's anything I can do to help get it over the line!

**Comment by seancorfield** [comment]
The changes since 0.13.0 are mostly around the use of `clojure.spec` and that's changed from `clojure.spec` to `clojure.spec.alpha` -- that's why you're seeing that failure. I'm not sure whether we should just update `clj-time.spec` to use the "alpha" namespace or not -- it affects which Alpha of Clojure 1.9 it works with. That said, `clojure.java.jdbc` is relying on the "alpha" version so there is a Contrib precedent.

**Comment by seancorfield** [comment]
I have updated master to depend on Clojure 1.9 Alpha 17 for testing and updated the `clj-time.spec` namespace to use the "alpha" namespaces. @AlexanderMann let me know if `master` works for you now. There's only one addition to the API since 0.13.0: `from-epoch`. We can consider a `0.13.1` release tho' if `master` is working for you...?

**Comment by AlexanderMann** [comment]
Sean, I've had good luck using the backport of spec etc. elsewhere. I'll
give it a shot probably tomorrow and let you know!

**Comment by seancorfield** [comment]
The backport of spec will not have the "alpha" namespaces I suspect -- `clj-time.spec` is only meant to work with Clojure 1.9 Alpha 17 (which is what we have in production at World Singles, BTW).

**Comment by AlexanderMann** [comment]
Yeah, I'd be using it in prod at circleci but alas, my lib is depended upon
by the monolith (shudder).

**Comment by AlexanderMann** [comment]
Didn't get to this today. Everything decided to break in other parts of my code. Should have a good chance at this tomorrow morning.

**Comment by AlexanderMann** [comment]
Tackling this now. The backport version has all the necessary tooling so I'm expecting this to be nicely straightforward.

**Comment by AlexanderMann** [comment]
@seancorfield `lein install`'ed all the things and my tests look quite happy. This worked excellently with the backport. If you decide to make a cut sometime soon I'll be happy to bump our dependencies to use it.

Cheers!

**Comment by seancorfield** [comment]
Pushed 0.14.0 to Clojars!
