### ISSUE TITLE
date format keeps static date if unparse receives a nil date argument

### ISSUE THREAD

**Issue by jeffmad** [clj-time/clj-time#247]
Hi I was surprised by this behavior, it might be a defect or just improper use of the api.  I solved it for my case by wrapping the call to unparse with a when. 

user> (require '[clj-time.format :as tf])
nil
user> (require '[clj-time.core :as tc])
nil
user> (def my-date-format (tf/formatter "yyyy-MM-dd"))
#'user/my-date-format
user> (def the-date (tc/now))
#'user/the-date
user> (tf/unparse my-date-format the-date)
"2018-03-16"
user> (tf/unparse my-date-format nil)
"2018-03-16"
user>

**Comment by seancorfield** [comment]
It's the behavior of Joda Time. The `unparse` function just calls the `.print` method: https://github.com/clj-time/clj-time/blob/master/src/clj_time/format.clj#L200-L204

But this has come up several times -- along with other functions that have "odd" behavior with `nil` because "That's What Joda Time Does(tm)" -- so it probably warrants a note in the README at this point.
