### ISSUE TITLE
`clj-time.core/equal?` returns unexpected value.

### ISSUE THREAD

**Issue by johanmynhardt** [clj-time/clj-time#262]
I have dug around for quite a while to determine whether it should be submitted as an issue or whether it's just me doing something wrong.

My actual issue issue started out with the curious result of evaluating the following:

```clojure
(ns my-ns
  (:require
    [clj-time.core :as t]))
,,,
(let [now (t/now)
      test-date nil]
  (t/within? now (t/minus now (t/days 5)) test-date))
```

Evaluating the let-block several times returned both `true` and `false`.

With further digging I ended up at `clj-time.core/equal?` and evaluating the following several times:

```clojure

(t/equal? (t/now) nil)
```
also happens to return `true` and `false`.

I don't know what the expectation should be, but I looked at the tests and it doesn't cover a case where the `that` argument is `nil`. IMO it should not return true ever if the second argument happens to be `nil`, especially since the documentation states:

> "Returns true if ReadableDateTime 'this' is strictly equal to date/time 'that'."

I'm happy to create a fix and PR if my reasoning is correct. 😄

**Comment by seancorfield** [comment]
From the README: "`clj-time` is a very thin wrapper around Joda Time. That means that if Joda Time has a "peculiar behavior", it's likely to be surfaced directly in `clj-time` as well. A good example of this is `clj-time.format/unparse` which simply calls Joda Time's `.print` method -- and if the date passed in happens to be `nil`, you silently get back the current date/time (many people would expect an exception!)."

In this case, `equal?` simply calls Joda Time's `.isEqual` method so you're seeing "peculiar behavior" from Joda Time here.

Also from the README: "If you are using Java 8 or later, consider using the built-in Java Time instead of Joda Time -- and look at `clojure.java-time` if you want a Clojure wrapper for that." -- which is another reason why issues like this won't get fixed.
