### ISSUE TITLE
Add support for Instant literals (introduced in Clojure 1.4)

### ISSUE THREAD

**Issue by jacobemcken** [clj-time/clj-time#93]
I solved the problem for my own use case with the following:

```
(defmethod print-dup org.joda.time.DateTime
  [^org.joda.time.DateTime d out]
  (print-dup (.toDate d) out))

(defmethod print-method org.joda.time.DateTime
  [^org.joda.time.DateTime d out]
  (print-method (.toDate d) out))
```

If the above is a general solution I do not know.

Also the above seems work well with Clojure versions prior to version 1.4 because Clojure falls back to using .toString instead.

Some might find the following relevant reading:
http://stackoverflow.com/questions/17554560/how-to-print-time-as-inst

**Comment by seancorfield** [comment]
Given clj-time only tests against 1.6 and 1.7 right now, it seems reasonable to reconsider this on the grounds that 1.4 Is way old...?

**Comment by timvisher** [comment]
@seancorfield :+1:

**Comment by seancorfield** [comment]
I would consider #149 somewhat related to this (since that is also about date interop) and note that #113 mentioned above only got closed because no one has submitted a PR for it after a year.

@michaelklishin do you want to go ahead with adding the Joda type support from Monger / ClojureWerkz directly to clj-time? If yes, and you want to do that under a separate, unified ticket, you might as well close this and #149 I think?

**Comment by michaelklishin** [comment]
@seancorfield I'm all for moving [monger.joda-time](https://github.com/michaelklishin/monger/blob/master/src/clojure/monger/joda_time.clj) to `clj-time`. I'd prefer to do that in a separate issue from this and #149, though.

**Comment by seancorfield** [comment]
OK, we'll close this out and I'll leave it up to you to create a separate ticket for that work. Thank you!

**Comment by jacobemcken** [comment]
I would love to subscribe to that new issue. 
If anyone remembers and would take the time to link it here it would be much appreciated :smile:

**Comment by michaelklishin** [comment]
@jacobemcken voilà: https://github.com/clj-time/clj-time/issues/179 :)
